export const productData=[
    {
      id: 1,
      img: 'krunchburger.png',
      title: "Krunch Burger",
      price: 195,
      desc: "Enjoy crispy chicken fillet in soft bun with spicy mayo & our signature sauce wiht fresh lettuce",
      quantity: 1,
      category: "everydayvalue",
      priceCategory: "lessfrom500",
      
    },
    {
      id: 2,
       img: 'riceandspice.png',
       title:"Rice And Spice",
       price: 270,
      desc: "Aromatic arabian rice with 6 pcs of hot shot wiht KFC's famous vietnames sauce.",
      quantity: 1,
      category: "everydayvalue",
      priceCategory: "lessfrom500",
    },
    {
      id: 3,
      img: 'burgerwithdrink.png',
      title:"Krunch Burger",
      price: 270,
      desc: "1 Krunch burger, with 1 regular drink.",
      quantity: 2,
      category: "everydayvalue",
      priceCategory: "lessfrom500",
    },
    {
      id: 4,
      img: 'twister.png',
      title:"Twister",
      price: 350,
      desc: "2 zinger strips drizzled with mayo, tomatoes and fresh lettuce,wrapped in a lighty toasted.",
      quantity: 2,
      category: "makeitmeal",
      priceCategory: "lessfrom500",
    },
    {
      id: 5,
      img: 'mightyzinger.png',
      title:"MIGHTY ZINGER",
      price: 595,
      desc: "2 whole zingers with spcicy mayo,cheese and fresh lettuce, all bundled in a Mighty bun.",
      quantity: 2,
      category: "makeitmeal",
      priceCategory: "lessfrom1000",
    },
    {
      id: 6,
      img: 'freshfries.png',
      title:"FRESH FRIES",
      price: 190,
      desc: "Enjoy our crispy fries also with your favorite KFC meal.",
      quantity: 2,
      category: "Snacks",
      priceCategory: "lessfrom500",
    },  
    {
      id: 7,
       img: 'hotshots.png',
       title:"HOT SHOTS 9 PCS",
       price: 300,
       desc: "They're tasty, they're hot, they're 9 pieces of HOT SHOTS and they're absolutly delectable.",
      quantity: 1,
      category: "Snacks",
      priceCategory: "lessfrom500",
    },
    {
      id: 8,
      img: 'midnightdeal1.png',
      title:"MIDNIGHT DEAL 1",
      price: 460,
      desc: "2 ( two ) Mighty Zinger + 2 ( two ) Regular Drink.",
      quantity: 2,
      category: "midnightdeal",
      priceCategory: "lessfrom500",
    },
  ];
